// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbeywwrykszqkgtuixze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZXl3d3J5a3N6cWtndHVpeHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzAyNTgsImV4cCI6MjA3MTcwNjI1OH0.rAA7SkbshzcLKOzbYOMJYWpyvAsNwAI8yP594tiPP5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});